
name: Ruby-Verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  rake-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby-version:
          - '3.1'
          - '3.4'
        os: 
          - ubuntu-latest
          - fedora-latest
          - macos-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake test
