
name: Ruby-Verify

# A Verify Pipeline for Ruby projects.

# Runs 'bundle exec rake test' for a Ruby-based project 
# setup like a typical gem.

# Caches the bundle install step to speed up the workflow.

# Runs on Ubuntu, Fedora, MacOS, and Windows.
# Runs on an array of Ruby versions.

on:
  pull_request:
  push:
    branches: 
      - "main"

permissions:
  contents: read

jobs:
  rake-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby-version:
          - '3.1'
          - '3.4'
        os: 
          - ubuntu-latest
          - fedora-latest
          - macos-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake test
